In [3]:
!pip install numpy
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [28]:
d = np.arange(1,13).reshape((3,4))
print(d)
d.ndim

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2

In [9]:
e = np.arange(1,11,2)
print(e)

[1 3 5 7 9]


In [14]:
c.shape

(2, 2, 3)

In [29]:
c.ndim

3

In [35]:
np.arange(48).reshape(2,2,3,4)

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]],


       [[[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]],

        [[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]]])

## indexing as slicing

In [36]:
a1 = np.arange(10)
print(a1)
print()
a2 = np.arange(12).reshape(3,4)
print(a2)
print()
a3 = np.arange(8).reshape(2,2,2)
print(a3)
print()

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]



In [38]:
a1[5]

5

In [39]:
a2[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [47]:
a2[1:,0::3]

array([[ 4,  7],
       [ 8, 11]])

In [53]:
a3[1,1,0:]

array([6, 7])

In [54]:
a3[0,1,1]

3

In [56]:
a4 = np.arange(27).reshape(3,3,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [57]:
a4[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [61]:
a4[::2,2]

array([[ 6,  7,  8],
       [24, 25, 26]])

In [59]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[76, 25, 36, 13],
       [70, 23, 11, 94],
       [53, 15, 54, 15],
       [49, 63, 58, 16],
       [61,  2, 16, 67],
       [55, 61, 49, 45]])

In [60]:
a[a%2 != 0]

array([25, 13, 23, 11, 53, 15, 15, 49, 63, 61, 67, 55, 61, 49, 45])